spring.mongodb.uri=mongodb+srv://niteshpokhrel84_db_user:AbO57gnDNmXPk828@cluster0.gbyqe3x.mongodb.net/?appName=Cluster0
spring.mongodb.database = student_management_system
spring.data.application.name= student_management_system
spring.data.mongodb.auto-index-creation=true
